services:
  backend:
      image: docker/dev-environments-javascript:stable-1
    ports:
      - 2000:2000
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - public
      - private
    depends_on:
      - db
  db:
    image: postgres:15.1
    restart: always
    container_name: Hive
    environment:
      - POSTGRES_USER=hornet
      - POSTGRES_PASSWORD=hornet
      - POSTGRES_DB=HIVE
    networks:
      - private
  networks:
    public:
    private:
